# Generated by Django 5.2.5 on 2025-08-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
