# Generated by Django 5.2.5 on 2025-08-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
