# Generated by Django 5.2.5 on 2025-08-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
